from box import Box

START_URL = {
    "CommercialBankShare": Box({
        "file_location" : {
            "W":"../../../../../data/commercialBank/weekly.json",
            "M": "../../../../../data/commercialBank/monthly.json",
            "Y": "../../../../../data/commercialBank/yearly.json",
            "Q": "../../../../../data/commercialBank/quaterly.json",
            "D": "../../../../../data/commercialBank/daily.json"
        },
        "links": [ 
            {"name": "Agriculture Development Bank Limited", "symbol": "ADBL", "value": 397},
            {"name": "Bank of Kathmandu Ltd", "symbol": "BOKL", "value": 138},
            {"name": "Century Commercial Bank Ltd", "symbol": "CCBL", "value": 605},
            {"name": "Citizen Bank International Limited", "symbol": "CZBIL", "value": 348},
            {"name": "Civil Bank Ltd", "symbol":"CBL", "value": 532},
            {"name":"Everest Bank Limited", "symbol": "EBL", "value": 137},
            {"name": "Global IME Bank Limited", "symbol": "GBIME", "value": 341},
            {"name": "Himalayan Bank Limited", "symbol": "HBL", "value": 134}, 
            {"name": "Kumari Bank Limited", "symbol": "KBL", "value": 142},
            {"name": "Laxmi Bank Limited", "symbol": "LBL", "value": 141},
            {"name": "Machhapuchhre Bank Limited", "symbol": "MBL", "value": 140},
            {"name": "Mega Bank Nepal Ltd", "symbol": "MEGA", "value": 562},
            {"name": "Nabil Bank Limited", "symbol": "NABIL", "value": 131},
            {"name": "Nepal Bangladesh Bank Limited", "symbol": "NBB", "value": 136},
            {"name": "Nepal Bank Limited", "symbol": "NBL", "value": 517},
            {"name": "Nepal Credit And Commercial Bank Limited", "symbol": "NCCB", "value": 144},
            {"name": "Nepal Investment Bank Limited", "symbol": "NIB", "value": 132},
            {"name": "Nepal SBI Bank Limited", "symbol": "SBI", "value": 135},
            {"name": "NIC Asia Bank Ltd", "symbol": "NICA", "value": 139},
            {"name": "NMB Bank Limited", "symbol": "NMB", "value": 238},
            {"name": "Prabhu Bank Limited", "symbol": "PRVU", "value": 255},
            {"name": "Prime Commercial Bank Ltd", "symbol": "PCBL", "value": 357},
            {"name": "Sanima Bank Limited", "symbol": "SANIMA", "value":171},
            {"name": "Siddhartha Bank Limited", "symbol": "SBL", "value": 145}, 
            {"name": "Standard Chartered Bank Limited", "symbol": "SCB", "value":133},
            {"name": "Sunrise Bank Limited", "symbol": "SRBL", "value": 359}
        ]}),
    "DevelopmentBank": Box({
        "file_location":{
            "W":"../../../../../data/developmentBank/weekly.json",
            "M": "../../../../../data/developmentBank/monthly.json",
            "Y": "../../../../../data/developmentBank/yearly.json",
            "Q": "../../../../../data/developmentBank/quaterly.json",
            "D": "../../../../../data/developmentBank/daily.json"
        },
        "links": [
            {"name": "Corporate Development Bank Limited", "symbol": "CORBL", "value": 450},
            {"name": "Deva Bikas Bank Limited", "symbol": "DBBL", "value": 311},
            {"name": "Excel Development Bank Ltd", "symbol": "EDBL", "value": 274},
            {"name": "Gandaki Bikas Bank Limited", "symbol": "GDBL", "value": 420},
            {"name": "Garima Bikas Bank Limited", "symbol": "GBBL", "value": 417},
            {"name": "Green Development Bank Ltd", "symbol": "GRDBL", "value": 2744},
            {"name": "Jyoti Bikas Bank Limited", "symbol": "JBBL", "value": 418},
            {"name": "Kamana Sewa Bikas Bank Limited", "symbol": "KSBBL", "value": 459}, 
            {"name": "Kanchan Development Bank Limited", "symbol": "KADBL", "value": 505},
            {"name": "Karnali Development Bank Limited", "symbol": "KRBL", "value": 428},
            {"name": "Lumbini Bikas Bank Ltd", "symbol": "LBBL", "value": 358},
            {"name": "Mahalaxmi Bikas Bank Ltd", "symbol": "MLBL", "value": 401},
            {"name": "Miteri Development Bank Limited", "symbol": "MDB", "value": 371},
            {"name": "Muktinath Bikas Bank Ltd", "symbol": "MNBBL", "value": 474},
            {"name": "Narayani Development Bank Limited", "symbol": "NABBC", "value": 172},
            {"name": "Nepal Community Development Bank Ltd", "symbol": "NCDB", "value": 598},
            {"name": "Sahara Bikas Bank Ltd", "symbol": "SHBL", "value": 625},
            {"name": "Sahayogi Bikas Bank Limited", "symbol": "SBBLJ", "value": 174},
            {"name": "Saptakoshi Development Bank Ltd", "symbol": "SAPDBL","value": 2860},
            {"name": "Shangrila Development Bank Ltd", "symbol": "SADBL","value": 472},
            {"name": "Shine Resunga Development Bank Ltd", "symbol": "SHINE", "value": 473},
            {"name": "Sindhu Bikash Bank Ltd", "symbol": "SINDU", "value": 561},
            {"name": "Tinau Mission Development Bank Limited", "symbol": "TMDBL", "value": 2855}
        ]}),
    "FinancialBankShare": Box({
        "file_location" : {
            "W":"../../../../../data/financialCompanies/weekly.json",
            "M": "../../../../../data/financialCompanies/monthly.json",
            "Y": "../../../../../data/financialCompanies/yearly.json",
            "Q": "../../../../../data/financialCompanies/quaterly.json",
            "D": "../../../../../data/financialCompanies/daily.json"
        },
        "links": [ 
            {"name": "Best Finance Company Ltd", "symbol": "BFC", "value": 227},
            {"name": "Capital Merchant Bank & Finance Co. Ltd", "symbol": "CMB", "value": 259},
            {"name": "Central Finance Co. Ltd", "symbol": "CFCL", "value": 245},
            {"name": "City Express Finance Co. Limited", "symbol": "CEFL", "value": 296},
            {"name": "Crystal Finance Ltd", "symbol": "CFL", "value": 361},
            {"name": "Goodwill Finance Co. Ltd", "symbol": "GFCL", "value": 232},
            {"name": "Guheshowori Merchant Bank & Finance Co. Ltd", "symbol": "GMFIL","value": 263},
            {"name": "Gurkhas Finance Ltd", "symbol": "GUFL", "value": 204},
            {"name": "ICFC Finance Limited", "symbol": "ICFC", "value": 273},
            {"name": "Janaki Finance Ltd", "symbol": "JFL", "value": 250},
            {"name": "Lalitpur Finance Ltd.", "symbol": "LFC", "value": 231},
            {"name": "Manjushree Finance Ltd", "symbol": "MFIL", "value": 516},
            {"name": "Multipurpose Finance Company Limited", "symbol": "MPFL", "value": 471},
            {"name": "Nepal Finance Ltd.", "symbol": "NFS", "value": 194},
            {"name": "Nepal Share Markets Ltd.", "symbol": "NSM", "value": 200},
            {"name": "Pokhara Finance Ltd", "symbol": "PFL", "value": 236},
            {"name": "ProgressiveFinance Limited", "symbol": "PROFL", "value": 338},
            {"name": "Reliance Finance Ltd.", "symbol": "RLFL", "value": 587},
            {"name": "Samriddhi Finance Company Limited", "symbol": "SFCL", "value":256},
            {"name": "Shree Investment Finance Co. Ltd.", "symbol": "SIFC", "value": 244},
            {"name": "Shrijana Finance (Bittaya Sanstha)", "symbol": "SFFIL", "value": 261},
            {"name": "Synergy Finance Ltd.", "symbol": "SYFL", "value": 249},
            {"name": "United Finance Ltd.", "symbol": "UFL", "value": 242}
        ]}),
    "MicroFinance": Box({
        "file_location": {
            "W":"../../../../../data/microfinance/weekly.json",
            "M": "../../../../../data/microfinance/monthly.json",
            "Y": "../../../../../data/microfinance/yearly.json",
            "Q": "../../../../../data/microfinance/quaterly.json",
            "D": "../../../../../data/microfinance/daily.json"
        },
        "links": [
            {"name": "Adhikhola Laghubitta Bittiya Sanstha Limited", "symbol": "AKBSL", "value": 2845},
            {"name": "Arambha Microfinance Bittiya Sanstha Ltd", "symbol": "AMFI", "value": 2777},
            {"name": "Asha Laghubitta Bittiya Sanstha Ltd", "symbol": "ALBSL", "value": 2807},
            {"name": "Chhimek Laghubitta Bittiya Sanstha Limited", "symbol": "CBBL", "value": 164},
            {"name": "Deprosc Laghubitta Bittiya Sanstha Limited", "symbol": "DDBL", "value": 166},
            {"name": "First Micro Finance Laghubitta Bittiya Sanstha Ltd.", "symbol": "FMDBL", "value": 490},
            {"name": "Kalika Laghubitta Bittiya Sanstha Limited", "symbol":"KMCDB", "value":593},
            {"name": "Nerude Laghubita Bikas Bank Limited", "symbol": "NLBBL", "value": 396},
            {"name": "Nirdhan Utthan Laghubitta Bittiya Sanstha Limited", "symbol": "NUBL", "value": 163},
            {"name": "RMDC Laghubitta Bittiya Sanstha Limited", "symbol": "RMDC", "value": 575},
            {"name": "Sana Kisan Bikas Laghubitta Bittiya sanstha Limited", "symbol": "SKBBL", "value": 574},
            {"name": "Swarojgar Laghubitta Bittiya Sanstha Ltd.", "symbol": "SLBBL", "value": 545},
            {"name": "Summit Laghubitta Bittiya Sanstha Ltd.", "symbol": "SMFDB", "value": 502},
            {"name": "Swabalamban Laghubitta Bittiya Sanstha Limited", "symbol": "SWBBL", "value":268},
            {"name": "Mithila Laghubitta Bittiya Sanstha Ltd.", "symbol": "MLBBL", "value":601},
            {"name": "Laxmi Laghubitta Bittiya Sanstha Ltd.", "symbol": "LLBS", "value": 618},
            {"name": "Mirmire Laghubitta Bittiya Sanstha Ltd.", "symbol": "MMFDB", "value": 682},
            {"name": "Janautthan Samudayic Laghubitta Bikas Bank Ltd.", "symbol": "JSLBB", "value": 695},
            {"name": "Womi Microfinance Bittiya Sanstha Ltd.", "symbol": "WOMI", "value": 706},
            {"name": "Vijaya laghubitta Bittiya Sanstha Ltd.", "symbol": "VLBS", "value": 687 },
            {"name": "RSDC Laghubitta Bittiya Sanstha Ltd.", "symbol": "RSDC", "value": 2748},
            {"name": "NMB Laghubitta Bittiya Sanstha Ltd.", "symbol": "NMBMF", "value": 704},
            {"name": "Meromicrofinance Laghubitta Bittiya Sanstha Ltd.", "symbol": "MERO", "value": 1741},
            {"name": "National Microfinance Laghubitta Bittiya Sanstha Ltd.", "symbol": "NMFBS", "value": 2746},
            {"name": "Suryodaya Laghubitta Bittiya Sanstha Ltd.", "symbol": "SLBS", "value": 2750},
            {"name": "Ganapati Microfinance Bittiya Sanstha Ltd", "symbol": "GMFBS", "value": 2815},
            {"name": "Civil Laghubitta Bittiya Sanstha Ltd.", "symbol": "CLBSL", "value": 693}
        ]
    })
}

